### ISSUE TITLE
lxml package need to be installed

### ISSUE THREAD

**Issue by f-is-h** [IvanWoo/douban-exporter-lite#1]
Init script didn't install lxml package.

**Comment by IvanWoo** [comment]
Hey @coolcooldool, thanks for the reporting! 

The issue has been fixed at [b594226](https://github.com/IvanWoo/douban-exporter-lite/commit/b59422677ab30024d9a8c72ea3683deefdac99ae).

**Comment by f-is-h** [comment]
Thanks! @IvanWoo
